# Generated by Django 5.0.6 on 2024-07-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='is_firstRegister',
            field=models.BooleanField(default=True),
        ),
    ]
