# Generated by Django 5.0.6 on 2024-07-24 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materiales_enlaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('path', models.TextField()),
                ('fecha', models.DateField()),
                ('id_anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.materiales')),
            ],
        ),
    ]
