# Generated by Django 5.0.6 on 2024-07-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_profesor_is_firstregister'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='is_firstRegister',
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_firstRegister',
            field=models.BooleanField(default=True),
        ),
    ]
