# Generated by Django 5.0.6 on 2024-07-24 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_materiales_enlaces'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materiales',
            old_name='titulo',
            new_name='tema',
        ),
    ]
