# Generated by Django 5.0.6 on 2024-07-10 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0003_remove_profesor_is_firstregister_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncios_links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField()),
                ('fecha', models.DateField()),
                ('id_anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.anuncios')),
            ],
        ),
    ]
