# Generated by Django 5.0.6 on 2024-06-26 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='usuario',
            new_name='id_usuario_id',
        ),
        migrations.RenameField(
            model_name='profesor',
            old_name='usuario',
            new_name='id_usuario_id',
        ),
    ]
